# use us_state['statename'][0-9]
# format is state: (x,y)
# no support for alaska and hawaii
us_state = {
    'Alabama': (2000,854, 510, 270),
    'Arizona': (615, 740, 510, 340),
    'Arkansas': (663, 677, 450, 390),
    'California': (147,425,667,594),
    'Colorado': (959, 493, 510, 270),
    'Connecticut': (,),
    'Delaware': (,),
    'Florida': (,),
    'Georgia': (,),
    'Idaho': (,),
    'Illinois': (,),
    'Indiana': (,),
    'Iowa': (,),
    'Kansas': (1361, 500, 510, 270),
    'Kentucky': (,),
    'Louisiana': (,),
    'Maine': (,),
    'Maryland': (,),
    'Massachusetts': (,),
    'Michigan': (,),
    'Minnesota': (,),
    'Mississippi': (,),
    'Missouri': (,),
    'Montana': (,),
    'Nebraska': (,),
    'Nevada': (,),
    'New Hampshire': (,),
    'New Jersey': (,),
    'New Mexico': (,),
    'New York': (,),
    'North Carolina': (,),
    'North Dakota': (,),
    'Ohio': (,),
    'Oklahoma': (,),
    'Oregon': (,),
    'Pennsylvania': (,),
    'Rhode Island': (,),
    'South Carolina': (,),
    'South Dakota': (,),
    'Tennessee': (,),
    'Texas': (,),
    'Utah': (,),
    'Vermont': (,),
    'Virginia': (,),
    'Washington': (,),
    'West Virginia': (,),
    'Wisconsin': (,),
    'Wyoming': (,),
}
